"use client";
// AI Smart Features — Cash Flow Forecast, Dynamic Pricing, Customer Churn Risk
// and Automated PO Drafts, surfaced on the AI Forecast page.
import { useToast } from "@/app/components/ToastProvider";
import Loading from "@/app/components/Loading";
import api, { markHandled } from "@/lib/api";
import { useState } from "react";

interface CashFlowBucket {
  period: string;
  openingBalance: number;
  inflows: number;
  outflows: number;
  netCashFlow: number;
  closingBalance: number;
}
interface CashFlowReport {
  summary: string;
  buckets: CashFlowBucket[];
  liquidityRisks: {
    level: string;
    month: string;
    description: string;
    recommendedAction: string;
  }[];
  keyActions: string[];
}

interface PricingRec {
  productId: number;
  product: string;
  direction: "RAISE" | "HOLD" | "DISCOUNT";
  currentSellPrice: number;
  suggestedSellPrice: number;
  suggestedDiscountPct: number | null;
  reason: string;
  expectedImpact: string;
}
interface PricingReport {
  summary: string;
  recommendations: PricingRec[];
  marginStrategy: string[];
}

interface ChurnItem {
  customerId: number;
  name: string;
  risk: "HIGH" | "MEDIUM" | "LOW";
  daysInactive: number;
  outstandingCredit: number;
  suggestedWinBackOffer: string;
  expectedRecoveryValue: number;
}
interface ChurnReport {
  summary: string;
  atRisk: ChurnItem[];
  retentionStrategy: string[];
}

interface PoDraftLine {
  productId: number;
  product: string;
  currentStock: number;
  suggestedQty: number;
  unitPrice: number;
  estimatedCost: number;
  urgency: "CRITICAL" | "HIGH" | "NORMAL";
}
interface PoDraft {
  id: number;
  supplier: string | null;
  status: "DRAFT" | "SUBMITTED";
  items: PoDraftLine[];
  estimatedTotal: number;
  autoGenerated: boolean;
  notes: string | null;
  createdAt: string;
}

const fmt = (n: number | null | undefined) =>
  n == null ? "—" : n.toLocaleString(undefined, { maximumFractionDigits: 0 });

const RISK_BADGE: Record<string, string> = {
  HIGH: "bg-red-100 text-red-700",
  MEDIUM: "bg-amber-100 text-amber-700",
  LOW: "bg-emerald-100 text-emerald-700",
};
const DIR_BADGE: Record<string, string> = {
  RAISE: "bg-emerald-100 text-emerald-700",
  HOLD: "bg-gray-100 text-gray-600",
  DISCOUNT: "bg-red-100 text-red-700",
};

export default function AiSmartFeatures() {
  const toast = useToast();
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [cashFlow, setCashFlow] = useState<CashFlowReport | null>(null);
  const [pricing, setPricing] = useState<PricingReport | null>(null);
  const [churn, setChurn] = useState<ChurnReport | null>(null);
  const [drafts, setDrafts] = useState<PoDraft[]>([]);

  const run = async (key: string, fn: () => Promise<void>) => {
    setBusy(key);
    setError("");
    try {
      await fn();
    } catch (err: any) {
      markHandled(err);
      setError(
        err?.response?.data?.message ||
          "Something went wrong. Please try again.",
      );
      if (err?.response?.status === 429) toast.error("Daily AI limit reached.");
    } finally {
      setBusy(null);
    }
  };

  const loadDrafts = () =>
    api.get("/ai/po-drafts").then((r) => setDrafts(r.data ?? []));

  const generateCashFlow = () =>
    run("cashflow", async () => {
      const res = await api.post(
        "/ai/cashflow",
        { targetPeriod: "NEXT_30_DAYS" },
        { timeout: 120000 },
      );
      setCashFlow(res.data.report);
    });

  const generatePricing = () =>
    run("pricing", async () => {
      const res = await api.post("/ai/pricing", {}, { timeout: 120000 });
      setPricing(res.data.report);
    });

  const generateChurn = () =>
    run("churn", async () => {
      const res = await api.post("/ai/churn", {}, { timeout: 120000 });
      setChurn(res.data.report);
    });

  const generatePoDraft = () =>
    run("podraft", async () => {
      await api.post("/ai/po-drafts", { autoCreate: true }, { timeout: 120000 });
      await loadDrafts();
    });

  const submitDraft = async (id: number) => {
    await api.post(`/ai/po-drafts/${id}/submit`);
    await loadDrafts();
  };

  const deleteDraft = async (id: number) => {
    await api.delete(`/ai/po-drafts/${id}`);
    await loadDrafts();
  };

  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-lg font-bold text-gray-800">✨ AI Smart Features</h2>
        <p className="text-sm text-gray-500">
          Cash flow projections, dynamic pricing, churn risk and automated
          purchase order drafts from your live data.
        </p>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 text-sm rounded-lg px-4 py-3">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* --- Cash flow --- */}
        <Panel
          icon="💵"
          title="Cash Flow Forecast"
          desc="30–90 day liquidity from live sales velocity minus COGS, overhead expenses and purchase outflows."
          actionLabel={busy === "cashflow" ? "Analyzing…" : "Generate Cash Flow"}
          onAction={generateCashFlow}
          busy={busy === "cashflow"}
        >
          {cashFlow && (
            <div className="space-y-3 mt-3">
              <p className="text-sm text-gray-700">{cashFlow.summary}</p>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-[11px] text-gray-500 uppercase">
                      <th className="pb-1">Period</th>
                      <th className="pb-1">Opening</th>
                      <th className="pb-1">In</th>
                      <th className="pb-1">Out</th>
                      <th className="pb-1">Net</th>
                      <th className="pb-1">Closing</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {cashFlow.buckets.map((b) => (
                      <tr key={b.period}>
                        <td className="py-1.5 font-medium text-gray-700">
                          {b.period.replace("NEXT_", "Next ").replace("_", " ")}
                        </td>
                        <td className="py-1.5">{fmt(b.openingBalance)}</td>
                        <td className="py-1.5 text-emerald-600">
                          +{fmt(b.inflows)}
                        </td>
                        <td className="py-1.5 text-red-600">
                          −{fmt(b.outflows)}
                        </td>
                        <td className="py-1.5">{fmt(b.netCashFlow)}</td>
                        <td className="py-1.5 font-semibold">
                          {fmt(b.closingBalance)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {cashFlow.liquidityRisks.length > 0 && (
                <ul className="space-y-2">
                  {cashFlow.liquidityRisks.map((r, i) => (
                    <li
                      key={i}
                      className="rounded-lg border border-gray-200 p-3 text-sm"
                    >
                      <span
                        className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                          RISK_BADGE[r.level] ?? "bg-gray-100 text-gray-600"
                        }`}
                      >
                        {r.level}
                      </span>{" "}
                      <span className="text-gray-700">{r.description}</span>
                      <p className="text-gray-500 mt-1">
                        → {r.recommendedAction}
                      </p>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}
        </Panel>

        {/* --- Dynamic pricing --- */}
        <Panel
          icon="🏷️"
          title="Dynamic Pricing"
          desc="Margin protection — price raises on rising purchase costs, discounts for slow-moving stock."
          actionLabel={busy === "pricing" ? "Analyzing…" : "Get Pricing Plan"}
          onAction={generatePricing}
          busy={busy === "pricing"}
        >
          {pricing && (
            <div className="space-y-3 mt-3">
              <p className="text-sm text-gray-700">{pricing.summary}</p>
              <ul className="divide-y divide-gray-100 max-h-72 overflow-y-auto">
                {pricing.recommendations.map((r) => (
                  <li key={r.productId} className="py-2 text-sm">
                    <div className="flex flex-wrap items-center gap-2">
                      <span
                        className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                          DIR_BADGE[r.direction] ?? "bg-gray-100"
                        }`}
                      >
                        {r.direction}
                      </span>
                      <span className="font-medium text-gray-800">
                        {r.product}
                      </span>
                      <span className="text-gray-400 text-xs">
                        {r.currentSellPrice} →{" "}
                        <span className="text-gray-700">
                          {r.suggestedSellPrice}
                        </span>{" "}
                        ETB
                        {r.suggestedDiscountPct
                          ? ` (−${r.suggestedDiscountPct}%)`
                          : ""}
                      </span>
                    </div>
                    <p className="text-gray-500 text-xs mt-0.5">{r.reason}</p>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </Panel>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* --- Churn --- */}
        <Panel
          icon="🧲"
          title="Customer Churn Risk"
          desc="Buying-pattern insights with win-back offers for inactive clients."
          actionLabel={busy === "churn" ? "Analyzing…" : "Analyze Churn"}
          onAction={generateChurn}
          busy={busy === "churn"}
        >
          {churn && (
            <div className="space-y-3 mt-3">
              <p className="text-sm text-gray-700">{churn.summary}</p>
              <ul className="divide-y divide-gray-100 max-h-72 overflow-y-auto">
                {churn.atRisk.map((c) => (
                  <li key={c.customerId} className="py-2 text-sm">
                    <div className="flex flex-wrap items-center gap-2">
                      <span
                        className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                          RISK_BADGE[c.risk] ?? "bg-gray-100"
                        }`}
                      >
                        {c.risk}
                      </span>
                      <span className="font-medium text-gray-800">
                        {c.name}
                      </span>
                      <span className="text-gray-400 text-xs">
                        {c.daysInactive} days inactive
                      </span>
                    </div>
                    <p className="text-gray-500 text-xs mt-0.5">
                      🎁 {c.suggestedWinBackOffer}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </Panel>

        {/* --- PO drafts --- */}
        <Panel
          icon="📦"
          title="Automated PO Drafts"
          desc="Auto-generated purchase order drafts when items hit reorder thresholds."
          actionLabel={busy === "podraft" ? "Generating…" : "Generate PO Draft"}
          onAction={generatePoDraft}
          busy={busy === "podraft"}
          onOpen={loadDrafts}
        >
          {drafts.length === 0 ? (
            <p className="text-sm text-gray-400 mt-3">
              No purchase order drafts yet. Generate one to auto-collect the
              items below their reorder threshold.
            </p>
          ) : (
            <ul className="divide-y divide-gray-100 mt-3 max-h-72 overflow-y-auto">
              {drafts.map((d) => (
                <li key={d.id} className="py-2 text-sm">
                  <div className="flex flex-wrap items-center gap-2">
                    <span
                      className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                        d.status === "SUBMITTED"
                          ? "bg-emerald-100 text-emerald-700"
                          : "bg-blue-100 text-blue-700"
                      }`}
                    >
                      {d.status}
                    </span>
                    <span className="font-medium text-gray-800">
                      PO #{d.id}
                      {d.supplier ? ` · ${d.supplier}` : ""}
                    </span>
                    <span className="text-gray-500 text-xs">
                      {fmt(d.estimatedTotal)} ETB · {d.items.length} item(s)
                    </span>
                  </div>
                  <p className="text-gray-500 text-xs mt-0.5">
                    {d.items
                      .map((i) => `${i.product} ×${i.suggestedQty}`)
                      .slice(0, 4)
                      .join(", ")}
                    {d.items.length > 4 ? "…" : ""}
                  </p>
                  {d.notes && (
                    <p className="text-[11px] text-blue-700 bg-blue-50 rounded px-2 py-1 mt-1">
                      💰 {d.notes}
                    </p>
                  )}
                  {d.status === "DRAFT" && (
                    <div className="flex gap-2 mt-1.5">
                      <button
                        onClick={() => submitDraft(d.id)}
                        className="text-xs bg-blue-600 text-white px-2.5 py-1 rounded-md hover:bg-blue-700"
                      >
                        Mark Submitted
                      </button>
                      <button
                        onClick={() => deleteDraft(d.id)}
                        className="text-xs bg-gray-100 text-gray-600 px-2.5 py-1 rounded-md hover:bg-gray-200"
                      >
                        Delete
                      </button>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          )}
        </Panel>
      </div>
    </div>
  );
}

function Panel({
  icon,
  title,
  desc,
  actionLabel,
  onAction,
  busy,
  onOpen,
  children,
}: {
  icon: string;
  title: string;
  desc: string;
  actionLabel: string;
  onAction: () => void;
  busy: boolean;
  onOpen?: () => void;
  children: React.ReactNode;
}) {
  const [opened, setOpened] = useState(false);
  const handleOpen = () => {
    if (!opened) {
      setOpened(true);
      onOpen?.();
    }
  };
  return (
    <div className="bg-white rounded-xl border shadow-sm p-4 sm:p-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold text-gray-800">
            {icon} {title}
          </h3>
          <p className="text-xs text-gray-500 mt-0.5">{desc}</p>
        </div>
        <button
          onClick={() => {
            handleOpen();
            onAction();
          }}
          disabled={busy}
          className="shrink-0 bg-blue-600 text-white text-xs font-medium px-3 py-2 rounded-lg hover:bg-blue-700 disabled:opacity-50"
        >
          {busy ? (
            <span className="inline-flex items-center gap-1.5">
              <Loading size="sm" /> {actionLabel}
            </span>
          ) : (
            actionLabel
          )}
        </button>
      </div>
      {children}
    </div>
  );
}



