"use client";
// Purchase Orders — where the AI-created purchase order drafts are reachable.
//
// The nightly sweep (and the AI Forecast button) stores a draft and raises a
// PO_DRAFT alert, but the draft itself only rendered inside that page panel,
// which never opened on its own — so the alert could not be acted upon. This
// page is where the bell now points: it lists every draft, prints one as a
// supplier order sheet and marks it ordered or drops it.
import Link from "next/link";
import Loading from "@/app/components/Loading";
import { useConfirm } from "@/app/components/ConfirmProvider";
import { useToast } from "@/app/components/ToastProvider";
import { useAuth } from "@/context/AuthContext";
import api, { markHandled } from "@/lib/api";
import { fmtCurrency } from "@/lib/currency";
import { formatDate } from "@/lib/datetime";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useTranslation } from "react-i18next";

interface PoDraftLine {
  productId: number;
  product: string;
  currentStock: number;
  suggestedQty: number;
  unitPrice: number;
  estimatedCost: number;
  urgency: "CRITICAL" | "HIGH" | "NORMAL";
}

interface PoDraft {
  id: number;
  supplier: string | null;
  status: "DRAFT" | "SUBMITTED";
  items: PoDraftLine[];
  estimatedTotal: number;
  autoGenerated: boolean;
  notes: string | null;
  createdAt: string;
}

type StatusFilter = "ALL" | "DRAFT" | "SUBMITTED";

const URGENCY_BADGE: Record<string, string> = {
  CRITICAL: "bg-red-100 text-red-700",
  HIGH: "bg-amber-100 text-amber-700",
  NORMAL: "bg-gray-100 text-gray-600",
};

const URGENCY_KEY: Record<string, string> = {
  CRITICAL: "purchaseOrders.urgencyCritical",
  HIGH: "purchaseOrders.urgencyHigh",
  NORMAL: "purchaseOrders.urgencyNormal",
};

const FILTERS: { value: StatusFilter; labelKey: string }[] = [
  { value: "ALL", labelKey: "purchaseOrders.filterAll" },
  { value: "DRAFT", labelKey: "purchaseOrders.filterDraft" },
  { value: "SUBMITTED", labelKey: "purchaseOrders.filterSubmitted" },
];

export default function PurchaseOrdersPage() {
  const { t } = useTranslation();
  const toast = useToast();
  const confirm = useConfirm();
  const { user, hasPermission } = useAuth();
  const canView = Boolean(user?.isSuperuser || hasPermission("ai.view"));

  const [drafts, setDrafts] = useState<PoDraft[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [filter, setFilter] = useState<StatusFilter>("ALL");
  const [printDraft, setPrintDraft] = useState<PoDraft | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api.get("/ai/po-drafts");
      setDrafts(res.data ?? []);
    } catch (err: any) {
      markHandled(err);
      setError(err?.response?.data?.message || t("purchaseOrders.loadFail"));
    } finally {
      setLoading(false);
    }
  }, [t]);

  useEffect(() => {
    if (!canView) return;
    load();
  }, [canView, load]);

  const shown = useMemo(
    () => (filter === "ALL" ? drafts : drafts.filter((d) => d.status === filter)),
    [drafts, filter],
  );

  // Every mutation keeps the previous list on screen and only surfaces the API
  // message, so a failed submit never blanks the page.
  const run = async (key: string, action: () => Promise<void>) => {
    setBusy(key);
    try {
      await action();
    } catch (err: any) {
      markHandled(err);
      toast.error(
        err?.response?.data?.message || t("purchaseOrders.actionFail"),
      );
    } finally {
      setBusy(null);
    }
  };

  const generate = () =>
    run("generate", async () => {
      const res = await api.post(
        "/ai/po-drafts",
        { autoCreate: true },
        { timeout: 120000 },
      );
      if (res.data?.draft) {
        toast.success(t("purchaseOrders.generated", { id: res.data.draft.id }));
      } else {
        toast.info(t("purchaseOrders.noneBelowThreshold"));
      }
      await load();
    });

  const submit = (id: number) =>
    run(`submit-${id}`, async () => {
      await api.post(`/ai/po-drafts/${id}/submit`);
      await load();
    });

  const remove = async (id: number) => {
    if (!(await confirm(t("purchaseOrders.deleteConfirm", { id })))) return;
    await run(`delete-${id}`, async () => {
      await api.delete(`/ai/po-drafts/${id}`);
      toast.success(t("purchaseOrders.deleted"));
      await load();
    });
  };

  // Printing works the way the ledger and the QR sheets do: the sheet is
  // portalled into #print-root and globals.css hides the rest of the page while
  // that node exists, so the paper shows the order and nothing else.
  const print = (draft: PoDraft) => {
    setPrintDraft(draft);
    setTimeout(() => window.print(), 120);
  };

  // Drop the sheet once the dialog closes: the portal hides the app in print, so
  // leaving it mounted would make a later ⌘P print the stale order.
  useEffect(() => {
    const clear = () => setPrintDraft(null);
    window.addEventListener("afterprint", clear);
    return () => window.removeEventListener("afterprint", clear);
  }, []);

  if (!canView) {
    return (
      <p className="p-6 text-sm text-gray-500">{t("purchaseOrders.noAccess")}</p>
    );
  }

  return (
    <div className="p-4 sm:p-6 space-y-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-800">
            {t("purchaseOrders.title")}
          </h1>
          <p className="text-sm text-gray-500 max-w-2xl">
            {t("purchaseOrders.subtitle")}
          </p>
        </div>
        <div className="flex flex-wrap gap-2 shrink-0">
          <button
            onClick={load}
            disabled={loading}
            className="text-sm font-medium bg-white text-gray-700 border border-gray-200 px-3 py-2 rounded-lg hover:bg-gray-50 disabled:opacity-50"
          >
            {t("purchaseOrders.refresh")}
          </button>
          <button
            onClick={generate}
            disabled={busy === "generate"}
            className="text-sm font-medium bg-blue-600 text-white px-3 py-2 rounded-lg hover:bg-blue-700 disabled:opacity-50"
          >
            {busy === "generate"
              ? t("purchaseOrders.generating")
              : t("purchaseOrders.generate")}
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 text-sm rounded-lg px-4 py-3">
          {error}
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        {FILTERS.map((f) => (
          <button
            key={f.value}
            onClick={() => setFilter(f.value)}
            className={`text-xs font-medium px-3 py-1.5 rounded-full border ${
              filter === f.value
                ? "bg-blue-600 text-white border-blue-600"
                : "bg-white text-gray-600 border-gray-200 hover:bg-gray-50"
            }`}
          >
            {t(f.labelKey)}
          </button>
        ))}
      </div>

      {loading ? (
        <Loading />
      ) : shown.length === 0 ? (
        <div className="bg-white border border-gray-200 rounded-xl p-6 text-center">
          <p className="text-sm font-medium text-gray-700">
            {filter === "ALL"
              ? t("purchaseOrders.empty")
              : t("purchaseOrders.emptyFiltered")}
          </p>
          {filter === "ALL" && (
            <>
              <p className="text-xs text-gray-500 mt-1">
                {t("purchaseOrders.emptyHint")}
              </p>
              <Link
                href="/dashboard/forecast"
                className="inline-block mt-3 text-sm font-medium text-blue-600 hover:text-blue-700"
              >
                {t("nav.aiForecast")}
              </Link>
            </>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          {shown.map((draft) => (
            <div
              key={draft.id}
              className="bg-white border border-gray-200 rounded-xl p-4 space-y-3"
            >
              <div className="flex flex-wrap items-center gap-2">
                <span
                  className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                    draft.status === "SUBMITTED"
                      ? "bg-emerald-100 text-emerald-700"
                      : "bg-blue-100 text-blue-700"
                  }`}
                >
                  {draft.status === "SUBMITTED"
                    ? t("ai.statusSubmitted")
                    : t("ai.statusDraft")}
                </span>
                <span className="font-semibold text-gray-800">
                  {t("ai.poRef", { id: draft.id })}
                </span>
                {draft.autoGenerated && (
                  <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-purple-100 text-purple-700">
                    {t("purchaseOrders.autoGenerated")}
                  </span>
                )}
                <span className="text-xs text-gray-500">
                  {t("purchaseOrders.createdAt", {
                    date: formatDate(draft.createdAt),
                  })}
                </span>
              </div>

              <div className="flex flex-wrap gap-x-5 gap-y-1 text-xs text-gray-600">
                <span>
                  {t("purchaseOrders.supplier")}:{" "}
                  {draft.supplier || t("purchaseOrders.supplierNone")}
                </span>
                <span>
                  {t("purchaseOrders.estimatedTotal")}:{" "}
                  <span className="font-semibold text-gray-800">
                    {fmtCurrency(draft.estimatedTotal, 2)}
                  </span>
                </span>
              </div>

              <div className="overflow-x-auto">
                {/* One line per cell: a currency figure used to break after "ETB"
                    and a product name onto two rows, leaving ragged whitespace in
                    the row. The container scrolls instead. */}
                <table className="w-full min-w-[44rem] text-xs border-collapse whitespace-nowrap">
                  <thead>
                    <tr className="text-left text-gray-500 border-b border-gray-200">
                      <th className="py-1.5 pr-3 font-medium">
                        {t("purchaseOrders.colProduct")}
                      </th>
                      <th className="py-1.5 px-3 font-medium text-right">
                        {t("purchaseOrders.colStock")}
                      </th>
                      <th className="py-1.5 px-3 font-medium text-right">
                        {t("purchaseOrders.colQty")}
                      </th>
                      <th className="py-1.5 px-3 font-medium text-right">
                        {t("purchaseOrders.colPrice")}
                      </th>
                      <th className="py-1.5 px-3 font-medium text-right">
                        {t("purchaseOrders.colCost")}
                      </th>
                      <th className="py-1.5 px-3 font-medium">
                        {t("purchaseOrders.colUrgency")}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {draft.items.map((line, idx) => (
                      <tr key={`${line.productId}-${idx}`} className="border-b border-gray-100">
                        <td className="py-1.5 pr-3 text-gray-800">{line.product}</td>
                        <td className="py-1.5 px-3 text-right tabular-nums">
                          {line.currentStock}
                        </td>
                        <td className="py-1.5 px-3 text-right tabular-nums font-medium">
                          {line.suggestedQty}
                        </td>
                        <td className="py-1.5 px-3 text-right tabular-nums">
                          {fmtCurrency(line.unitPrice, 2)}
                        </td>
                        <td className="py-1.5 px-3 text-right tabular-nums">
                          {fmtCurrency(line.estimatedCost, 2)}
                        </td>
                        <td className="py-1.5 px-3">
                          <span
                            className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                              URGENCY_BADGE[line.urgency] ?? "bg-gray-100 text-gray-600"
                            }`}
                          >
                            {t(URGENCY_KEY[line.urgency] ?? "purchaseOrders.urgencyNormal")}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {draft.notes && (
                <p className="text-[11px] text-blue-700 bg-blue-50 rounded px-2 py-1">
                  {t("purchaseOrders.notesTitle")}: {draft.notes}
                </p>
              )}

              <div className="flex flex-wrap gap-2 pt-1">
                {draft.status === "DRAFT" && (
                  <button
                    onClick={() => submit(draft.id)}
                    disabled={busy === `submit-${draft.id}`}
                    className="text-xs font-medium bg-blue-600 text-white px-3 py-1.5 rounded-md hover:bg-blue-700 disabled:opacity-50"
                  >
                    {t("ai.markSubmitted")}
                  </button>
                )}
                <button
                  onClick={() => print(draft)}
                  className="text-xs font-medium bg-gray-100 text-gray-700 px-3 py-1.5 rounded-md hover:bg-gray-200"
                >
                  {t("purchaseOrders.print")}
                </button>
                <button
                  onClick={() => remove(draft.id)}
                  disabled={busy === `delete-${draft.id}`}
                  className="text-xs font-medium text-red-600 px-3 py-1.5 rounded-md hover:bg-red-50 disabled:opacity-50"
                >
                  {t("common.delete")}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {printDraft &&
        typeof document !== "undefined" &&
        createPortal(
          <div id="print-root">
            <div className="po-print-body">
              <div className="po-print-head">
                <div>
                  <h1 className="po-print-title">
                    {t("purchaseOrders.docTitle", { id: printDraft.id })}
                  </h1>
                  <p className="po-print-meta">
                    {t("purchaseOrders.createdAt", {
                      date: formatDate(printDraft.createdAt),
                    })}
                  </p>
                  <p className="po-print-meta">
                    {t("purchaseOrders.supplier")}:{" "}
                    {printDraft.supplier || t("purchaseOrders.supplierNone")}
                  </p>
                </div>
                <p className="po-print-meta">{t("ai.poRef", { id: printDraft.id })}</p>
              </div>
              <table className="po-print-table">
                <thead>
                  <tr>
                    <th>{t("purchaseOrders.colProduct")}</th>
                    <th className="po-print-num">{t("purchaseOrders.colStock")}</th>
                    <th className="po-print-num">{t("purchaseOrders.colQty")}</th>
                    <th className="po-print-num">{t("purchaseOrders.colPrice")}</th>
                    <th className="po-print-num">{t("purchaseOrders.colCost")}</th>
                    <th>{t("purchaseOrders.colUrgency")}</th>
                  </tr>
                </thead>
                <tbody>
                  {printDraft.items.map((line, idx) => (
                    <tr key={`${line.productId}-${idx}`}>
                      <td>{line.product}</td>
                      <td className="po-print-num">{line.currentStock}</td>
                      <td className="po-print-num">{line.suggestedQty}</td>
                      <td className="po-print-num">{fmtCurrency(line.unitPrice, 2)}</td>
                      <td className="po-print-num">{fmtCurrency(line.estimatedCost, 2)}</td>
                      <td>{t(URGENCY_KEY[line.urgency] ?? "purchaseOrders.urgencyNormal")}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <p className="po-print-total">
                {t("purchaseOrders.docTotal", {
                  total: fmtCurrency(printDraft.estimatedTotal, 2),
                })}
              </p>
              {printDraft.notes && (
                <p className="po-print-note">
                  {t("purchaseOrders.notesTitle")}: {printDraft.notes}
                </p>
              )}
              <p className="po-print-note">{t("purchaseOrders.docNote")}</p>
            </div>
          </div>,
          document.body,
        )}
    </div>
  );
}
