// prisma/seed-shop-catalog.ts
// Shared catalog data for the five standalone demo shops. Imported by both
// prisma/seed.ts (dev, wipes DB) and prisma/seed-prod.ts (idempotent).

export interface SeedVariant {
  attributes: Record<string, string>;
  sku: string;
  barcode: string;
  buyPrice: number;
  sellPrice: number;
  qty: number;
}

export interface SeedProduct {
  sku: string;
  brand: string;
  baseName: string;
  category: string;
  unit: string;
  buyPrice: number;
  sellPrice: number;
  variants: SeedVariant[];
}

export interface SeedShop {
  orgName: string;
  slug: string;
  owner: { email: string; name: string; password: string; phone: string };
  shopName: string;
  categories: string[];
  units: string[];
  products: SeedProduct[];
}

// Numeric EAN-style barcodes, globally unique across all tenants.
let bc = 610000000000;
const barcode = () => String(bc++);

function expand(
  sku: string,
  brand: string,
  baseName: string,
  category: string,
  unit: string,
  buy: number,
  sell: number,
  combos: Record<string, string>[],
  qty: number,
): SeedProduct {
  return {
    sku,
    brand,
    baseName,
    category,
    unit,
    buyPrice: buy,
    sellPrice: sell,
    variants: combos.map((attributes, i) => ({
      attributes,
      sku: `${sku}-V${i + 1}`,
      barcode: barcode(),
      buyPrice: buy,
      sellPrice: sell,
      qty,
    })),
  };
}

// size x color combos
const sc = (sizes: string[], colors: string[]) =>
  sizes.flatMap((size) => colors.map((color) => ({ size, color })));
// age/size x color combos
const ac = (ages: string[], colors: string[]) =>
  ages.flatMap((age) => colors.map((color) => ({ age, color })));
// color-only
const co = (colors: string[]) => colors.map((color) => ({ color }));
// single standard variant
const single = () => [{ model: 'standard' }];

export const SHOPS: SeedShop[] = [
  // ---------------------------------------------------------------------------
  // 1. Temesgen Aleme's Footwear Shop
  // ---------------------------------------------------------------------------
  {
    orgName: "Temesgen Aleme's Footwear Shop",
    slug: 'temesgen-footwear',
    owner: {
      email: 'teme@gmail.com',
      name: 'Temesgen Aleme',
      password: 'TEST@1234',
      phone: '+251911000001',
    },
    shopName: 'Temesgen Footwear Shop',
    categories: [
      'Mens Footwear',
      'Womens Footwear',
      'Formal Shoes',
      'Boots',
      'Sports Shoes',
    ],
    units: ['Pair'],
    products: [
      expand(
        'FWT-URBAN-STRIDE',
        'Urban Stride',
        "Men's Casual Sneaker",
        'Mens Footwear',
        'Pair',
        18,
        40,
        sc(['40', '42', '44'], ['Black', 'White']),
        8,
      ),
      expand(
        'FWT-TRAILBLAZE',
        'TrailBlaze',
        "Men's Hiking Shoe",
        'Mens Footwear',
        'Pair',
        30,
        65,
        sc(['41', '43', '45'], ['Brown', 'Grey']),
        6,
      ),
      expand(
        'FWT-EVERYDAY-LOAFER',
        'Everyday',
        "Men's Leather Loafer",
        'Mens Footwear',
        'Pair',
        25,
        55,
        sc(['40', '42', '44'], ['Brown', 'Black']),
        7,
      ),
      expand(
        'FWT-FLEXRUN',
        'FlexRun',
        "Men's Running Shoe",
        'Mens Footwear',
        'Pair',
        22,
        48,
        sc(['40', '42', '44'], ['Blue', 'Red']),
        9,
      ),
      expand(
        'FWT-GRACE-FLAT',
        'Grace',
        "Women's Ballet Flat",
        'Womens Footwear',
        'Pair',
        15,
        35,
        sc(['36', '38', '40'], ['Black', 'Nude']),
        8,
      ),
      expand(
        'FWT-ELEGANCE-WEDGE',
        'Elegance',
        "Women's Wedge Sandal",
        'Womens Footwear',
        'Pair',
        20,
        45,
        sc(['36', '38', '40', '41'], ['Tan', 'White']),
        6,
      ),
      expand(
        'FWT-BLOOM-RUN',
        'Bloom',
        "Women's Running Shoe",
        'Womens Footwear',
        'Pair',
        22,
        48,
        sc(['36', '38', '40'], ['Pink', 'Purple']),
        9,
      ),
      expand(
        'FWT-SERENITY-SANDAL',
        'Serenity',
        "Women's Comfort Sandal",
        'Womens Footwear',
        'Pair',
        16,
        38,
        sc(['36', '37', '38', '39'], ['Brown', 'Black']),
        7,
      ),
      expand(
        'FWT-EXECUTIVE-OXFORD',
        'Executive',
        "Men's Oxford Shoe",
        'Formal Shoes',
        'Pair',
        40,
        85,
        sc(['40', '42', '44'], ['Black']),
        5,
      ),
      expand(
        'FWT-CLASSIC-DERBY',
        'Classic',
        "Men's Derby Shoe",
        'Formal Shoes',
        'Pair',
        35,
        78,
        sc(['39', '41', '43'], ['Brown']),
        5,
      ),
      expand(
        'FWT-LADY-LUXE-PUMP',
        'Lady Luxe',
        "Women's Pump Heel",
        'Formal Shoes',
        'Pair',
        28,
        62,
        sc(['36', '38', '40'], ['Black', 'Nude']),
        6,
      ),
      expand(
        'FWT-GENTLEMAN-MONK',
        'Gentleman',
        "Men's Monk Strap Shoe",
        'Formal Shoes',
        'Pair',
        38,
        82,
        sc(['40', '42', '44'], ['Tan', 'Brown']),
        5,
      ),
      expand(
        'FWT-RUGGED-WORKBOOT',
        'Rugged',
        "Men's Work Boot",
        'Boots',
        'Pair',
        45,
        95,
        sc(['40', '42', '44', '45'], ['Brown', 'Black']),
        6,
      ),
      expand(
        'FWT-TREK-LEATHERBOOT',
        'Trek',
        "Men's Leather Boot",
        'Boots',
        'Pair',
        50,
        105,
        sc(['41', '43', '45'], ['Brown']),
        5,
      ),
      expand(
        'FWT-SNOWLINE-WINTER',
        'Snowline',
        "Women's Winter Boot",
        'Boots',
        'Pair',
        32,
        72,
        sc(['36', '38', '40', '41'], ['Black', 'Grey']),
        6,
      ),
      expand(
        'FWT-DESERT-CHUKKA',
        'Desert',
        "Men's Chukka Boot",
        'Boots',
        'Pair',
        28,
        62,
        sc(['39', '41', '43'], ['Tan']),
        6,
      ),

      expand(
        'SPT-ACE-TENNIS',
        'Ace',
        'Court Tennis Shoe',
        'Sports Shoes',
        'Pair',
        24,
        52,
        sc(['40', '42', '44'], ['White', 'Green']),
        8,
      ),
      expand(
        'SPT-COURTSTAR-BBALL',
        'CourtStar',
        'Basketball Shoe',
        'Sports Shoes',
        'Pair',
        35,
        78,
        sc(['41', '43', '45'], ['Black', 'Red']),
        6,
      ),
      expand(
        'SPT-JOGPRO-RUNNER',
        'JogPro',
        'Running Shoe',
        'Sports Shoes',
        'Pair',
        20,
        45,
        sc(['40', '42', '44'], ['Grey', 'Orange']),
        10,
      ),
      expand(
        'SPT-FIELDKING-FOOTBALL',
        'FieldKing',
        'Football Boot',
        'Sports Shoes',
        'Pair',
        26,
        58,
        sc(['39', '41', '43'], ['Black', 'White']),
        7,
      ),
    ],
  },
  // ---------------------------------------------------------------------------
  // ---------------------------------------------------------------------------
  // 2. Mussie's Kids & Baby World
  // ---------------------------------------------------------------------------
  {
    orgName: "Mussie's Kids & Baby World",
    slug: 'mussie-kids-baby',
    owner: {
      email: 'mus@gmail.com',
      name: 'Mussie Kebede',
      password: 'TEST@1234',
      phone: '+251911000002',
    },
    shopName: 'Kids & Baby World',
    categories: [
      'Baby Clothing',
      'Baby Footwear',
      'Bicycles & Tricycles',
      'Baby Accessories & Toys',
    ],
    units: ['Piece', 'Pair', 'Unit'],
    products: [
      expand(
        'KBY-COTTON-ONESIE',
        'Little Bloom',
        'Cotton Baby Onesie',
        'Baby Clothing',
        'Piece',
        3.5,
        8,
        ac(['0-3M', '3-6M', '6-12M'], ['White', 'Yellow', 'Pink']),
        12,
      ),
      expand(
        'KBY-BABY-ROMPER',
        'Little Bloom',
        'Baby Romper Suit',
        'Baby Clothing',
        'Piece',
        5,
        12,
        ac(['3-6M', '6-12M', '12-18M'], ['Blue', 'Green']),
        10,
      ),
      expand(
        'KBY-HAT-SOCK-SET',
        'CozyNest',
        'Baby Hat & Sock Set',
        'Baby Clothing',
        'Piece',
        2.5,
        6,
        ac(['0-6M', '6-12M'], ['Beige', 'Grey']),
        15,
      ),
      expand(
        'KBY-KNIT-CARDIGAN',
        'CozyNest',
        'Knit Baby Cardigan',
        'Baby Clothing',
        'Piece',
        6,
        14,
        ac(['6-12M', '12-18M', '18-24M'], ['Cream', 'Pink']),
        8,
      ),
      expand(
        'KBY-FOOTED-SLEEPSUIT',
        'Little Bloom',
        'Footed Baby Sleepsuit',
        'Baby Clothing',
        'Piece',
        4,
        10,
        ac(['0-3M', '3-6M', '6-12M'], ['Blue', 'White']),
        12,
      ),
      expand(
        'KBY-SOFTSOLE-FIRST',
        'TinyTread',
        'First Steps Soft Sole Shoe',
        'Baby Footwear',
        'Pair',
        4,
        10,
        ac(['0-6M', '6-12M'], ['White', 'Pink']),
        10,
      ),
      expand(
        'KBY-TODDLER-SANDAL',
        'TinyTread',
        'Toddler Sandal',
        'Baby Footwear',
        'Pair',
        5,
        12,
        ac(['1-2Y', '2-3Y'], ['Brown', 'Blue']),
        9,
      ),
      expand(
        'KBY-COZY-BABY-BOOTIE',
        'CozyNest',
        'Cozy Baby Bootie',
        'Baby Footwear',
        'Pair',
        3.5,
        8,
        ac(['0-3M', '3-6M'], ['Grey', 'Cream']),
        12,
      ),
      expand(
        'KBY-TODDLER-SNEAKER',
        'TinyTread',
        'Toddler Sneaker',
        'Baby Footwear',
        'Pair',
        7,
        16,
        ac(['1-2Y', '2-3Y'], ['Blue', 'Red']),
        10,
      ),
      expand(
        'KBY-BALANCE-BIKE',
        'Wheely',
        'Balance Bike 12"',
        'Bicycles & Tricycles',
        'Unit',
        25,
        55,
        co(['Red', 'Blue']),
        4,
      ),
      expand(
        'KBY-KIDS-TRICYCLE',
        'Wheely',
        'Kids Tricycle',
        'Bicycles & Tricycles',
        'Unit',
        30,
        65,
        co(['Green', 'Pink']),
        3,
      ),
      expand(
        'KBY-TRAINING-BIKE',
        'Wheely',
        'Training Wheels Bike 16"',
        'Bicycles & Tricycles',
        'Unit',
        45,
        95,
        co(['Blue', 'Black']),
        3,
      ),
      expand(
        'KBY-KICK-SCOOTER',
        'Wheely',
        'Kids Kick Scooter',
        'Bicycles & Tricycles',
        'Unit',
        20,
        45,
        co(['Purple', 'Teal']),
        5,
      ),
      expand(
        'KBY-MUSICAL-MOBILE',
        'PlayNest',
        'Musical Baby Mobile',
        'Baby Accessories & Toys',
        'Piece',
        8,
        18,
        single(),
        8,
      ),
      expand(
        'KBY-STACKING-RINGS',
        'PlayNest',
        'Stacking Rings Toy',
        'Baby Accessories & Toys',
        'Piece',
        5,
        12,
        single(),
        10,
      ),
      expand(
        'KBY-BABY-BOTTLE-SET',
        'NurseEase',
        'Baby Bottle Set',
        'Baby Accessories & Toys',
        'Piece',
        6,
        14,
        co(['Blue', 'Pink']),
        10,
      ),
      expand(
        'KBY-PLUSH-TEDDY',
        'PlayNest',
        'Plush Teddy Bear',
        'Baby Accessories & Toys',
        'Piece',
        4,
        10,
        sc(['Small', 'Large'], ['Brown']),
        8,
      ),
      expand(
        'KBY-RATTLE-TEETHER',
        'PlayNest',
        'Rattle & Teether Set',
        'Baby Accessories & Toys',
        'Piece',
        3,
        8,
        co(['Green', 'Yellow']),
        12,
      ),
      expand(
        'KBY-BATH-TOY-SET',
        'PlayNest',
        'Bath Toy Set',
        'Baby Accessories & Toys',
        'Piece',
        5,
        12,
        co(['Blue', 'Pink']),
        10,
      ),
      expand(
        'KBY-BABY-MONITOR',
        'NurseEase',
        'Video Baby Monitor',
        'Baby Accessories & Toys',
        'Piece',
        20,
        45,
        co(['White', 'Grey']),
        4,
      ),
    ],
  },
  // 3. Haile's Mobile & Accessories Shop
  // ---------------------------------------------------------------------------
  {
    orgName: "Haile's Mobile & Accessories Shop",
    slug: 'haile-mobile-accessories',
    owner: {
      email: 'haile@gmail.com',
      name: 'Haile Melaku',
      password: 'Haile@1234',
      phone: '+251911000003',
    },
    shopName: 'Mobile & Accessories Shop',
    categories: [
      'Smartphones',
      'Tablets',
      'Phone Accessories',
      'Audio & Headphones',
      'Charging & Power',
    ],
    units: ['Piece'],
    products: [
      expand(
        'MBL-PROMAX-5G',
        'TechnoStar',
        'ProMax 5G Smartphone',
        'Smartphones',
        'Piece',
        350,
        520,
        sc(['128GB', '256GB'], ['Black', 'Blue']),
        5,
      ),
      expand(
        'MBL-NOVA-LITE',
        'TechnoStar',
        'Nova Lite Smartphone',
        'Smartphones',
        'Piece',
        120,
        185,
        sc(['64GB', '128GB'], ['Blue', 'Green']),
        8,
      ),
      expand(
        'MBL-GALAXYA',
        'Samsung',
        'Galaxy A Series Phone',
        'Smartphones',
        'Piece',
        200,
        300,
        sc(['128GB'], ['Black', 'White']),
        6,
      ),
      expand(
        'MBL-TABPAD-10',
        'PadTech',
        'TabPad 10 Tablet',
        'Tablets',
        'Piece',
        150,
        240,
        sc(['64GB'], ['Grey', 'Black']),
        5,
      ),
      expand(
        'MBL-TABPAD-8',
        'PadTech',
        'TabPad 8 Tablet',
        'Tablets',
        'Piece',
        100,
        160,
        sc(['32GB'], ['Black', 'Blue']),
        6,
      ),
      expand(
        'MBL-SILICONE-CASE',
        'CasePro',
        'Silicone Phone Case',
        'Phone Accessories',
        'Piece',
        1.5,
        4,
        sc(['iPhone', 'Android'], ['Black', 'Clear', 'Blue']),
        20,
      ),
      expand(
        'MBL-GLASS-PROTECTOR',
        'CasePro',
        'Tempered Glass Protector',
        'Phone Accessories',
        'Piece',
        0.8,
        2.5,
        sc(['iPhone', 'Android'], ['Clear']),
        25,
      ),
      expand(
        'MBL-PHONE-STAND',
        'CasePro',
        'Desktop Phone Stand',
        'Phone Accessories',
        'Piece',
        2,
        5,
        co(['Black', 'White']),
        15,
      ),
      expand(
        'MBL-SMARTWATCH-STRAP',
        'WristPlus',
        'Smartwatch Strap',
        'Phone Accessories',
        'Piece',
        2.5,
        6,
        sc(['Small', 'Medium', 'Large'], ['Black', 'Blue']),
        12,
      ),
      expand(
        'MBL-MICROSD-128',
        'SanDisk',
        'Micro SD Card 128GB',
        'Phone Accessories',
        'Piece',
        8,
        15,
        single(),
        10,
      ),
      expand(
        'MBL-WIRELESS-EARBUDS',
        'SoundWave',
        'Wireless Earbuds',
        'Audio & Headphones',
        'Piece',
        12,
        28,
        co(['Black', 'White']),
        10,
      ),
      expand(
        'MBL-OVEREAR-HEADPHONES',
        'SoundWave',
        'Over-Ear Headphones',
        'Audio & Headphones',
        'Piece',
        22,
        48,
        co(['Black', 'Grey']),
        8,
      ),
      expand(
        'MBL-BLUETOOTH-SPEAKER',
        'BoomBox',
        'Bluetooth Speaker',
        'Audio & Headphones',
        'Piece',
        15,
        35,
        co(['Black', 'Blue', 'Red']),
        8,
      ),
      expand(
        'MBL-WIRED-EARPHONES',
        'SoundWave',
        'Wired Earphones',
        'Audio & Headphones',
        'Piece',
        3,
        7,
        co(['Black']),
        15,
      ),
      expand(
        'MBL-FAST-CHARGER-33',
        'PowerUp',
        'Fast Charger 33W',
        'Charging & Power',
        'Piece',
        5,
        12,
        single(),
        15,
      ),
      expand(
        'MBL-POWERBANK-20000',
        'PowerUp',
        'Power Bank 20000mAh',
        'Charging & Power',
        'Piece',
        14,
        30,
        co(['Black', 'White']),
        8,
      ),
      expand(
        'MBL-USBC-CABLE-1M',
        'CableMax',
        'USB-C Cable 1m',
        'Charging & Power',
        'Piece',
        1.2,
        3,
        co(['Black', 'White']),
        25,
      ),
      expand(
        'MBL-USBC-CABLE-2M',
        'CableMax',
        'USB-C Cable 2m',
        'Charging & Power',
        'Piece',
        1.5,
        3.5,
        co(['Black']),
        20,
      ),
      expand(
        'MBL-WIRELESS-CHARGER',
        'PowerUp',
        'Wireless Charger Pad',
        'Charging & Power',
        'Piece',
        8,
        18,
        co(['White', 'Black']),
        10,
      ),
      expand(
        'MBL-CAR-CHARGER',
        'PowerUp',
        'Car Charger Adapter',
        'Charging & Power',
        'Piece',
        3.5,
        8,
        co(['Black']),
        15,
      ),
    ],
  },

  // ---------------------------------------------------------------------------
  // 4. Meseret's Mobile & Accessories Shop (independent org)
  // ---------------------------------------------------------------------------
  {
    orgName: "Meseret's Mobile & Accessories Shop",
    slug: 'meseret-mobile-accessories',
    owner: {
      email: 'messi@gmail.com',
      name: 'Meseret Mulugeta',
      password: 'Messi@1234',
      phone: '+251911000004',
    },
    shopName: 'Mobile & Accessories Shop',
    categories: [
      'Smartphones',
      'Tablets',
      'Phone Accessories',
      'Audio & Headphones',
      'Charging & Power',
    ],
    units: ['Piece'],
    products: [
      expand(
        'MSG-ULTRA-X',
        'NovaCom',
        'Ultra X Smartphone',
        'Smartphones',
        'Piece',
        380,
        560,
        sc(['128GB', '256GB'], ['Midnight', 'Silver']),
        5,
      ),
      expand(
        'MSG-STAR-MINI',
        'NovaCom',
        'Star Mini Smartphone',
        'Smartphones',
        'Piece',
        100,
        160,
        sc(['64GB'], ['Black', 'Red']),
        8,
      ),
      expand(
        'MSG-ALPHA-5G',
        'NovaCom',
        'Alpha 5G Smartphone',
        'Smartphones',
        'Piece',
        250,
        380,
        sc(['128GB'], ['Black', 'Green']),
        6,
      ),
      expand(
        'MSG-SLATE-PRO',
        'PixelTab',
        'Slate Pro Tablet',
        'Tablets',
        'Piece',
        180,
        280,
        sc(['128GB'], ['Graphite']),
        4,
      ),
      expand(
        'MSG-SLATE-LITE',
        'PixelTab',
        'Slate Lite Tablet',
        'Tablets',
        'Piece',
        120,
        190,
        sc(['64GB'], ['Grey', 'Blue']),
        5,
      ),
      expand(
        'MSG-ARMOR-CASE',
        'ShieldLine',
        'Armor Phone Case',
        'Phone Accessories',
        'Piece',
        2,
        5,
        sc(['iPhone', 'Android'], ['Black', 'Green', 'Clear']),
        18,
      ),
      expand(
        'MSG-RING-HOLDER',
        'ShieldLine',
        'Phone Ring Holder Stand',
        'Phone Accessories',
        'Piece',
        1.5,
        4,
        co(['Black', 'Gold']),
        20,
      ),
      expand(
        'MSG-SELFIE-STICK',
        'ShieldLine',
        'Bluetooth Selfie Stick',
        'Phone Accessories',
        'Piece',
        6,
        14,
        co(['Black']),
        10,
      ),
      expand(
        'MSG-COOLER-FAN',
        'ShieldLine',
        'Phone Cooler Fan',
        'Phone Accessories',
        'Piece',
        5,
        12,
        co(['White']),
        8,
      ),
      expand(
        'MSG-SIM-TOOL-KIT',
        'ShieldLine',
        'SIM Ejector Tool Kit',
        'Phone Accessories',
        'Piece',
        0.5,
        1.5,
        single(),
        30,
      ),
      expand(
        'MSG-BASS-EARPHONES',
        'EchoSound',
        'Bass Wireless Earphones',
        'Audio & Headphones',
        'Piece',
        10,
        24,
        co(['Black', 'Blue']),
        12,
      ),
      expand(
        'MSG-STUDIO-HEADPHONES',
        'EchoSound',
        'Studio Headphones',
        'Audio & Headphones',
        'Piece',
        25,
        55,
        co(['Black', 'Red']),
        8,
      ),
      expand(
        'MSG-MINI-SPEAKER',
        'EchoSound',
        'Mini Bluetooth Speaker',
        'Audio & Headphones',
        'Piece',
        12,
        26,
        co(['Teal', 'Black']),
        10,
      ),
      expand(
        'MSG-GAMING-HEADSET',
        'EchoSound',
        'Gaming Headset',
        'Audio & Headphones',
        'Piece',
        18,
        40,
        co(['Black', 'Green']),
        8,
      ),
      expand(
        'MSG-TURBO-CHARGER-65',
        'VoltMax',
        'Turbo Charger 65W',
        'Charging & Power',
        'Piece',
        9,
        20,
        single(),
        12,
      ),
      expand(
        'MSG-POWERBANK-10000',
        'VoltMax',
        'Power Bank 10000mAh',
        'Charging & Power',
        'Piece',
        10,
        22,
        co(['Black', 'Blue']),
        12,
      ),
      expand(
        'MSG-USBA-CABLE-1M',
        'VoltMax',
        'USB-A Cable 1m',
        'Charging & Power',
        'Piece',
        1,
        2.5,
        co(['Black', 'White']),
        25,
      ),
      expand(
        'MSG-MULTIPORT-CHARGER',
        'VoltMax',
        'Multi-Port Charger',
        'Charging & Power',
        'Piece',
        7,
        16,
        co(['White']),
        10,
      ),
      expand(
        'MSG-MAGSAFE-POWERBANK',
        'VoltMax',
        'MagSafe Power Bank',
        'Charging & Power',
        'Piece',
        20,
        42,
        co(['Black', 'White']),
        6,
      ),
      expand(
        'MSG-SOLAR-POWERBANK',
        'VoltMax',
        'Solar Power Bank',
        'Charging & Power',
        'Piece',
        16,
        36,
        co(['Black']),
        5,
      ),
    ],
  },

  // ---------------------------------------------------------------------------
  // 5. Meseret's Cloths & Shoes Shop (independent org)
  // ---------------------------------------------------------------------------
  {
    orgName: "Meseret's Cloths & Shoes Shop",
    slug: 'meseret-cloths-shoes',
    owner: {
      email: 'messi@gmail.com',
      name: 'Meseret Mulugeta',
      password: 'Messi@1234',
      phone: '+251911000004',
    },
    shopName: 'Cloths & Shoes Shop',
    categories: [
      'Mens Clothing',
      'Womens Clothing',
      'Kids Clothing',
      'Shoes',
      'Bags & Accessories',
    ],
    units: ['Piece', 'Pair'],
    products: [
      expand(
        'CSH-COTTON-TSHIRT',
        'UrbanWear',
        'Classic Cotton T-Shirt',
        'Mens Clothing',
        'Piece',
        4,
        10,
        sc(['S', 'M', 'L', 'XL'], ['White', 'Black', 'Blue']),
        15,
      ),
      expand(
        'CSH-SLIM-JEANS',
        'UrbanWear',
        'Slim Fit Denim Jeans',
        'Mens Clothing',
        'Piece',
        12,
        28,
        sc(['30', '32', '34', '36'], ['Blue', 'Black']),
        10,
      ),
      expand(
        'CSH-CASUAL-SHIRT',
        'UrbanWear',
        'Casual Button Shirt',
        'Mens Clothing',
        'Piece',
        8,
        18,
        sc(['S', 'M', 'L', 'XL'], ['Check', 'Plain']),
        10,
      ),
      expand(
        'CSH-HOODED-SWEAT',
        'UrbanWear',
        'Hooded Sweatshirt',
        'Mens Clothing',
        'Piece',
        10,
        24,
        sc(['S', 'M', 'L', 'XL'], ['Grey', 'Black']),
        10,
      ),
      expand(
        'CSH-FLORAL-DRESS',
        'Femme',
        'Floral Summer Dress',
        'Womens Clothing',
        'Piece',
        12,
        28,
        sc(['S', 'M', 'L'], ['Floral', 'Plain']),
        10,
      ),
      expand(
        'CSH-LEGGINGS',
        'Femme',
        'Everyday Leggings',
        'Womens Clothing',
        'Piece',
        6,
        14,
        sc(['S', 'M', 'L'], ['Black', 'Navy']),
        12,
      ),
      expand(
        'CSH-BLOUSE',
        'Femme',
        'Elegant Blouse',
        'Womens Clothing',
        'Piece',
        8,
        18,
        sc(['S', 'M', 'L'], ['White', 'Pink']),
        10,
      ),
      expand(
        'CSH-DENIM-JACKET',
        'Femme',
        'Denim Jacket',
        'Womens Clothing',
        'Piece',
        15,
        35,
        sc(['S', 'M', 'L'], ['Blue', 'Black']),
        8,
      ),
      expand(
        'CSH-KIDS-TSHIRT',
        'TinyTrend',
        'Kids T-Shirt',
        'Kids Clothing',
        'Piece',
        3.5,
        8,
        ac(['2-3Y', '4-5Y', '6-7Y'], ['Red', 'Blue']),
        15,
      ),
      expand(
        'CSH-KIDS-JEANS',
        'TinyTrend',
        'Kids Denim Jeans',
        'Kids Clothing',
        'Piece',
        6,
        14,
        ac(['2-3Y', '4-5Y', '6-7Y'], ['Blue', 'Black']),
        10,
      ),
      expand(
        'CSH-KIDS-SWEATER',
        'TinyTrend',
        'Kids Knit Sweater',
        'Kids Clothing',
        'Piece',
        5,
        12,
        ac(['2-3Y', '4-5Y', '6-7Y'], ['Green', 'Yellow']),
        10,
      ),
      expand(
        'CSH-KIDS-SHORTS',
        'TinyTrend',
        'Kids Casual Shorts',
        'Kids Clothing',
        'Piece',
        4,
        10,
        ac(['2-3Y', '4-5Y'], ['Navy', 'Beige']),
        12,
      ),
      expand(
        'CSH-MENS-DRESSSHOE',
        'Apex',
        "Men's Dress Shoe",
        'Shoes',
        'Pair',
        25,
        55,
        sc(['40', '42', '44'], ['Black', 'Brown']),
        8,
      ),
      expand(
        'CSH-WOMENS-SANDAL',
        'Apex',
        "Women's Strappy Sandal",
        'Shoes',
        'Pair',
        10,
        24,
        sc(['36', '38', '40'], ['Tan', 'White']),
        10,
      ),
      expand(
        'CSH-KIDS-SPORTSSHOE',
        'Apex',
        'Kids Sports Shoe',
        'Shoes',
        'Pair',
        8,
        18,
        ac(['1-2Y', '3-4Y'], ['Blue', 'Red']),
        10,
      ),
      expand(
        'CSH-FLIP-FLOPS',
        'Apex',
        'Unisex Flip-Flops',
        'Shoes',
        'Pair',
        3,
        8,
        sc(['38', '40', '42', '44'], ['Black', 'Navy']),
        15,
      ),
      expand(
        'CSH-LEATHER-WALLET',
        'LeatherCraft',
        'Leather Wallet',
        'Bags & Accessories',
        'Piece',
        6,
        15,
        co(['Black', 'Brown']),
        10,
      ),
      expand(
        'CSH-SCHOOL-BACKPACK',
        'LeatherCraft',
        'School Backpack',
        'Bags & Accessories',
        'Piece',
        10,
        25,
        co(['Blue', 'Black', 'Red']),
        8,
      ),
      expand(
        'CSH-LEATHER-BELT',
        'LeatherCraft',
        'Leather Belt',
        'Bags & Accessories',
        'Piece',
        4,
        10,
        sc(['S', 'M', 'L'], ['Black', 'Brown']),
        12,
      ),
      expand(
        'CSH-SUNGLASSES',
        'LeatherCraft',
        'Fashion Sunglasses',
        'Bags & Accessories',
        'Piece',
        3,
        9,
        co(['Black', 'Brown']),
        12,
      ),
    ],
  },
  // ---------------------------------------------------------------------------
  // 6. Tamiru Taye's Tame Tools (standalone org)
  // ---------------------------------------------------------------------------
  {
    orgName: 'Tame Tools',
    slug: 'tame-tools',
    owner: {
      email: 'tame@gmail.com',
      name: 'Tamiru Taye',
      password: 'Tame@1234',
      phone: '+251911000005',
    },
    shopName: 'Tame Tools Shop',
    categories: [
      'Water Pumps',
      'Generators',
      'Demolition Tools',
      'Woodwork Machines',
      'Drills & Drivers',
      'Car Repair Tools',
    ],
    units: ['Piece', 'Unit'],
    products: [
      expand(
        'TL-SUBMERSIBLE-PUMP',
        'AquaMax',
        'Submersible Water Pump',
        'Water Pumps',
        'Unit',
        45,
        95,
        sc(['1HP', '1.5HP'], ['Black']),
        4,
      ),
      expand(
        'TL-BOOSTER-PUMP',
        'AquaMax',
        'Surface Booster Pump',
        'Water Pumps',
        'Unit',
        35,
        78,
        sc(['0.5HP', '1HP'], ['Black']),
        5,
      ),
      expand(
        'TL-DIESEL-PUMP',
        'PowerPro',
        'Diesel Water Pump',
        'Water Pumps',
        'Unit',
        150,
        320,
        sc(['3HP', '5HP'], ['Red']),
        3,
      ),
      expand(
        'TL-PETROL-GEN',
        'PowerPro',
        'Portable Petrol Generator',
        'Generators',
        'Unit',
        180,
        380,
        sc(['2.5kW', '3.5kW'], ['Yellow']),
        3,
      ),
      expand(
        'TL-DIESEL-GEN',
        'PowerPro',
        'Diesel Generator',
        'Generators',
        'Unit',
        450,
        950,
        sc(['5kW', '7.5kW'], ['Red']),
        2,
      ),
      expand(
        'TL-INVERTER-GEN',
        'PowerPro',
        'Inverter Generator',
        'Generators',
        'Unit',
        120,
        260,
        single(),
        2,
      ),
      expand(
        'TL-JACKHAMMER',
        'BreakerPro',
        'Jack Hammer Breaker',
        'Demolition Tools',
        'Unit',
        220,
        480,
        sc(['65mm', '90mm'], ['Blue']),
        2,
      ),
      expand(
        'TL-CHISEL-SET',
        'BreakerPro',
        'Demolition Chisel Set',
        'Demolition Tools',
        'Piece',
        12,
        28,
        single(),
        6,
      ),
      expand(
        'TL-CIRCULAR-SAW',
        'CutMaster',
        'Circular Saw 7"',
        'Woodwork Machines',
        'Piece',
        55,
        120,
        sc(['1200W', '1600W'], ['Orange']),
        5,
      ),
      expand(
        'TL-JIGSAW',
        'CutMaster',
        'Jig Saw 650W',
        'Woodwork Machines',
        'Piece',
        35,
        78,
        single(),
        5,
      ),
      expand(
        'TL-TABLE-SAW',
        'CutMaster',
        'Table Saw 10"',
        'Woodwork Machines',
        'Unit',
        140,
        300,
        sc(['1500W', '2000W'], ['Grey']),
        3,
      ),
      expand(
        'TL-WOOD-PLANER',
        'CutMaster',
        'Wood Planer 6"',
        'Woodwork Machines',
        'Unit',
        160,
        350,
        single(),
        2,
      ),
      expand(
        'TL-ANGLE-GRINDER',
        'CutMaster',
        'Angle Grinder 4.5"',
        'Woodwork Machines',
        'Piece',
        30,
        68,
        sc(['850W', '1100W'], ['Black']),
        6,
      ),
      expand(
        'TL-HAND-DRILL',
        'DriveWell',
        'Hand Drill 13mm',
        'Drills & Drivers',
        'Piece',
        25,
        58,
        sc(['550W', '750W'], ['Black']),
        6,
      ),
      expand(
        'TL-CORDLESS-DRILL',
        'DriveWell',
        'Cordless Drill Driver 18V',
        'Drills & Drivers',
        'Piece',
        45,
        98,
        sc(['1 Battery', '2 Batteries'], ['Green']),
        4,
      ),
      expand(
        'TL-IMPACT-DRIVER',
        'DriveWell',
        'Impact Driver 18V',
        'Drills & Drivers',
        'Piece',
        40,
        88,
        single(),
        4,
      ),
      expand(
        'TL-BIT-SET',
        'DriveWell',
        'Screwdriver Bit Set',
        'Drills & Drivers',
        'Piece',
        8,
        18,
        sc(['32pc', '58pc'], ['Grey']),
        8,
      ),
      expand(
        'TL-HYDRAULIC-JACK',
        'AutoFix',
        'Hydraulic Car Jack 2 Ton',
        'Car Repair Tools',
        'Unit',
        30,
        68,
        single(),
        5,
      ),
      expand(
        'TL-AIR-COMPRESSOR',
        'AutoFix',
        'Air Compressor 50L',
        'Car Repair Tools',
        'Unit',
        120,
        260,
        sc(['50L', '100L'], ['Blue']),
        3,
      ),
      expand(
        'TL-MECHANIC-KIT',
        'AutoFix',
        'Mechanic Tool Kit Set',
        'Car Repair Tools',
        'Piece',
        35,
        78,
        sc(['76pc', '118pc'], ['Red']),
        5,
      ),
    ],
  },
];
